name: Playwright cucumber Tests
on:
  #Trigger when code is pushed to main or master
  push:
    branches: [ main, master ]
  #Trigger when pull request is created
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '30 3 * * *'
jobs:
  test:
    # Job will stop if it runs more than 60 minutes
    timeout-minutes: 60
    # Creates Ubuntu virtual machine runner
    runs-on: ubuntu-latest
    steps:
      #Download repository code into runner
    - uses: actions/checkout@v4
      # Install Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # Install project dependencies from package.json
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # Create .env file dynamically using GitHub Secrets & Variables
    - name: Create .env file
      run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "FIRSTNAME=${{ vars.FIRSTNAME }}" >> .env
          echo "LASTNAME=${{ vars.LASTNAME }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "MOBILE_NUMBER=${{ secrets.MOBILE_NUMBER }}" >> .env
          echo "BIRTH_DATE=${{ vars.BIRTH_DATE }}" >> .env
          echo "BIRTH_MONTH=${{ vars.BIRTH_MONTH }}" >> .env
          echo "BIRTH_YEAR=${{ vars.BIRTH_YEAR }}" >> .env
          echo "FILL_SUBJECT=${{ vars.FILL_SUBJECT }}" >> .env
          echo "FILL_ADDRESS=${{ vars.FILL_ADDRESS }}" >> .env



    - name: Create reports folder
      run: mkdir -p reports


    - name: Run cucumber tests
      run: npm  test
      env:
        HEADLESS: 'true'
    # Upload reports as GitHub Artifact (Downloadable from Actions tab)
    - name: Upload Cucumber Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: reports/
        retention-days: 30
    - name: Send Test Report Email
      if: always()   # Send email even if test fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Playwright Cucumber Test Report"
        body: |
          Hello,
          
          The scheduled automation test execution has completed.
          
          Please find the attached HTML report.
          
          Regards,
          GitHub Actions
        to: bharathsha46@gmail.com
        from: ${{ secrets.EMAIL }}
        attachments: reports/html-report.html

    


